/**
 * e2e for `agentcomm install` — writes the harness wiring that drives the
 * globally installed CLI (issue #152). Claude gets a local plugin under
 * .claude/skills/, Codex gets its hooks file (foreign entries preserved),
 * OpenCode gets its auto-discovered plugin file. Static like `describe`:
 * never connects to a backend.
 *
 * The invariant under test throughout: what we write, we REWRITE. Wiring
 * generated by an older CLI must converge on re-run — that is the whole
 * reason this command replaced `hooks`.
 */
import { describe, it, expect, afterEach } from 'vitest';
import { promises as fs } from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';

const here = path.dirname(fileURLToPath(import.meta.url));
const cli = path.join(here, '..', 'src', 'cli.ts');
const tsx = pathToFileURL(createRequire(import.meta.url).resolve('tsx')).href;

const CLAUDE_DIR = '.claude/skills/agentcomm';
const CLAUDE_MANIFEST = `${CLAUDE_DIR}/.claude-plugin/plugin.json`;
const CLAUDE_HOOKS = `${CLAUDE_DIR}/hooks/hooks.json`;
const CODEX_FILE = '.codex/hooks.json';
const OPENCODE_FILE = '.opencode/plugin/agentcomm.ts';

const tmpRoots: string[] = [];
async function mkTmp(harnessDirs: string[] = []): Promise<string> {
  const dir = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), 'agentcomm-install-')));
  tmpRoots.push(dir);
  for (const d of harnessDirs) await fs.mkdir(path.join(dir, d), { recursive: true });
  return dir;
}
afterEach(async () => {
  for (const dir of tmpRoots.splice(0)) await fs.rm(dir, { recursive: true, force: true });
});

function run(args: string[], cwd: string): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, ['--import', tsx, cli, ...args], {
      stdio: ['ignore', 'pipe', 'pipe'],
      cwd,
      env: { ...process.env, AGENTCOMM_NO_GIT_PROBE: '1' },
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (d) => (stdout += d.toString()));
    child.stderr.on('data', (d) => (stderr += d.toString()));
    child.on('error', reject);
    child.on('exit', (code) => resolve({ code: code ?? -1, stdout, stderr }));
  });
}

const readJson = async (dir: string, file: string) =>
  JSON.parse(await fs.readFile(path.join(dir, file), 'utf8')) as Record<string, never>;
const exists = (dir: string, file: string) =>
  fs
    .stat(path.join(dir, file))
    .then(() => true)
    .catch(() => false);

describe('CLI install (harness wiring)', () => {
  it('--harness claude writes a local plugin and never touches settings.json', async () => {
    const dir = await mkTmp();
    const r = await run(['install', '--harness', 'claude', '--json'], dir);
    expect(r.code).toBe(0);
    expect(JSON.parse(r.stdout)).toMatchObject({
      mode: 'install',
      harnesses: [{ harness: 'claude', file: CLAUDE_DIR, state: 'written' }],
    });

    // A manifest is what makes the folder a plugin rather than a plain skill.
    const manifest = (await readJson(dir, CLAUDE_MANIFEST)) as unknown as { name: string; version: string };
    expect(manifest.name).toBe('agentcomm');
    expect(manifest.version).toMatch(/^\d+\.\d+\.\d+/);

    const { hooks } = (await readJson(dir, CLAUDE_HOOKS)) as unknown as { hooks: Record<string, unknown[]> };
    // The whole lifecycle, every command the global CLI:
    for (const event of ['SessionStart', 'SessionEnd', 'Stop', 'UserPromptSubmit', 'PostToolUse', 'TaskCreated', 'TaskCompleted']) {
      expect(hooks[event], event).toBeDefined();
    }
    expect(JSON.stringify(hooks)).toContain('agentcomm hook session-start');
    expect(JSON.stringify(hooks)).toContain('agentcomm hook stop-guard');

    // The point of the plugin route: the team's settings file stays ours-free.
    expect(await exists(dir, '.claude/settings.json')).toBe(false);
  });

  it('--harness codex writes .codex/hooks.json without the Claude-only task events', async () => {
    const dir = await mkTmp();
    const r = await run(['install', '--harness', 'codex', '--json'], dir);
    expect(r.code).toBe(0);
    expect(JSON.parse(r.stdout)).toMatchObject({ harnesses: [{ harness: 'codex', file: CODEX_FILE, state: 'written' }] });
    const { hooks } = (await readJson(dir, CODEX_FILE)) as unknown as { hooks: Record<string, unknown[]> };
    expect(hooks.SessionStart).toBeDefined();
    expect(hooks.TaskCreated).toBeUndefined(); // Codex has no task events
  });

  it('--harness opencode writes the local plugin that shells out to the CLI', async () => {
    const dir = await mkTmp();
    const r = await run(['install', '--harness', 'opencode', '--json'], dir);
    expect(r.code).toBe(0);
    expect(JSON.parse(r.stdout)).toMatchObject({ harnesses: [{ harness: 'opencode', file: OPENCODE_FILE, state: 'written' }] });

    const content = await fs.readFile(path.join(dir, OPENCODE_FILE), 'utf8');
    // The hooks drive the global CLI: register at session start, peek on idle.
    expect(content).toContain('agentcomm register');
    expect(content).toContain('agentcomm peek --json');
    expect(content).toContain("event.type !== 'session.idle'");
    expect(content).toContain("from '@opencode-ai/plugin'");
    // Telemetry parity (#115): tool events feed the CLI's rule matcher, and
    // dispose ships the spool. Matching stays CLI-side — the template only
    // normalizes payloads.
    expect(content).toContain('agentcomm hook telemetry');
    expect(content).toContain("'tool.execute.after'");
    for (const tool of ['skill', 'task', 'bash']) expect(content).toContain(`input.tool === '${tool}'`);
    expect(content).toContain('agentcomm emit --flush');
    expect(content).toContain('async dispose()');
  });

  it('wires every harness the repo visibly uses when none is named', async () => {
    const dir = await mkTmp(['.claude', '.codex', '.opencode']);
    const r = await run(['install', '--json'], dir);
    expect(r.code).toBe(0);
    const { harnesses } = JSON.parse(r.stdout) as { harnesses: { harness: string }[] };
    expect(harnesses.map((h) => h.harness)).toEqual(['claude', 'codex', 'opencode']);
    for (const f of [CLAUDE_MANIFEST, CODEX_FILE, OPENCODE_FILE]) expect(await exists(dir, f), f).toBe(true);
  });

  it('errors instead of guessing when no harness is present', async () => {
    const dir = await mkTmp();
    const r = await run(['install'], dir);
    expect(r.code).not.toBe(0);
    expect(r.stderr).toContain('--harness');
  });

  it('rejects an unknown harness', async () => {
    const dir = await mkTmp();
    const r = await run(['install', '--harness', 'cursor'], dir);
    expect(r.code).not.toBe(0);
    expect(r.stderr).toContain('cursor');
  });

  it('re-running is a no-op on disk', async () => {
    const dir = await mkTmp(['.claude', '.codex', '.opencode']);
    await run(['install'], dir);
    const before = await Promise.all(
      [CLAUDE_MANIFEST, CLAUDE_HOOKS, CODEX_FILE, OPENCODE_FILE].map((f) => fs.stat(path.join(dir, f))),
    );
    const again = await run(['install', '--json'], dir);
    const { harnesses } = JSON.parse(again.stdout) as { harnesses: { state: string }[] };
    expect(harnesses.every((h) => h.state === 'unchanged')).toBe(true);
    const after = await Promise.all(
      [CLAUDE_MANIFEST, CLAUDE_HOOKS, CODEX_FILE, OPENCODE_FILE].map((f) => fs.stat(path.join(dir, f))),
    );
    expect(after.map((s) => s.mtimeMs)).toEqual(before.map((s) => s.mtimeMs));
  });

  it('refreshes wiring an older CLI wrote — the upgrade path `hooks` never had', async () => {
    const dir = await mkTmp(['.claude', '.codex', '.opencode']);
    await run(['install'], dir);

    // Age every harness the way a release would: an older plugin version, a
    // stale hook command, a frozen OpenCode template.
    const manifestPath = path.join(dir, CLAUDE_MANIFEST);
    const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8')) as { version: string };
    await fs.writeFile(manifestPath, JSON.stringify({ ...manifest, version: '0.0.1' }, null, 2) + '\n');
    const codex = (await readJson(dir, CODEX_FILE)) as unknown as { hooks: Record<string, unknown[]> };
    codex.hooks.Stop = [{ hooks: [{ type: 'command', command: 'agentcomm hook stop-guard', timeout: 3 }] }];
    await fs.writeFile(path.join(dir, CODEX_FILE), JSON.stringify(codex, null, 2) + '\n');
    await fs.writeFile(path.join(dir, OPENCODE_FILE), '// generated by agentcomm 0.0.1\n');

    const stale = await run(['install', '--check', '--json'], dir);
    expect(stale.code).toBe(1);
    expect(JSON.parse(stale.stdout)).toMatchObject({ current: false });
    expect((JSON.parse(stale.stdout) as { harnesses: { state: string }[] }).harnesses.map((h) => h.state)).toEqual([
      'stale',
      'stale',
      'stale',
    ]);

    const fixed = await run(['install', '--json'], dir);
    expect((JSON.parse(fixed.stdout) as { harnesses: { state: string }[] }).harnesses.every((h) => h.state === 'written')).toBe(
      true,
    );
    expect(await run(['install', '--check'], dir).then((r) => r.code)).toBe(0);
    // The stale Codex timeout is gone, not duplicated alongside the fresh one.
    const refreshed = (await readJson(dir, CODEX_FILE)) as unknown as { hooks: { Stop: { hooks: unknown[] }[] } };
    expect(refreshed.hooks.Stop).toHaveLength(1);
    expect(JSON.stringify(refreshed.hooks.Stop)).toContain('"timeout":15');
  });

  it('--check reports missing wiring without writing it', async () => {
    const dir = await mkTmp(['.claude']);
    const r = await run(['install', '--check', '--json'], dir);
    expect(r.code).toBe(1);
    expect(JSON.parse(r.stdout)).toMatchObject({ mode: 'check', harnesses: [{ state: 'missing' }] });
    expect(await exists(dir, CLAUDE_MANIFEST)).toBe(false);
  });

  it('preserves foreign Codex hooks through install and uninstall', async () => {
    const dir = await mkTmp(['.codex']);
    const mine = { type: 'command', command: 'echo my-own-hook', timeout: 5 };
    await fs.writeFile(
      path.join(dir, CODEX_FILE),
      JSON.stringify({ note: 'keep me', hooks: { SessionStart: [{ hooks: [mine] }] } }, null, 2),
    );

    await run(['install'], dir);
    const wired = (await readJson(dir, CODEX_FILE)) as unknown as {
      note: string;
      hooks: { SessionStart: { hooks: unknown[] }[] };
    };
    expect(wired.note).toBe('keep me'); // non-hook keys untouched
    expect(wired.hooks.SessionStart).toHaveLength(2); // theirs, then ours
    expect(wired.hooks.SessionStart[0]!.hooks).toEqual([mine]);

    const gone = await run(['install', '--uninstall', '--json'], dir);
    expect(gone.code).toBe(0);
    expect(JSON.parse(gone.stdout)).toMatchObject({ mode: 'uninstall', harnesses: [{ state: 'removed' }] });
    const left = (await readJson(dir, CODEX_FILE)) as unknown as {
      note: string;
      hooks: { SessionStart: { hooks: unknown[] }[] };
    };
    expect(left.note).toBe('keep me');
    expect(left.hooks.SessionStart).toEqual([{ hooks: [mine] }]); // only ours removed
    expect(JSON.stringify(left)).not.toContain('agentcomm hook');
  });

  it('--uninstall leaves nothing of ours behind', async () => {
    const dir = await mkTmp(['.claude', '.codex', '.opencode']);
    await run(['install'], dir);
    const r = await run(['install', '--uninstall', '--json'], dir);
    expect(r.code).toBe(0);
    expect((JSON.parse(r.stdout) as { harnesses: { state: string }[] }).harnesses.every((h) => h.state === 'removed')).toBe(true);
    for (const f of [CLAUDE_DIR, CODEX_FILE, OPENCODE_FILE]) expect(await exists(dir, f), f).toBe(false);
    // Only the directories our own files occupied are pruned.
    expect(await exists(dir, '.claude')).toBe(true);
    expect(await exists(dir, '.claude/skills')).toBe(false);

    // Nothing of ours left to remove — say so instead of claiming a removal.
    const again = await run(['install', '--uninstall', '--harness', 'codex', '--json'], dir);
    expect(JSON.parse(again.stdout)).toMatchObject({ harnesses: [{ state: 'absent' }] });
  });

  it('refuses to clobber a hooks file it cannot parse', async () => {
    const dir = await mkTmp(['.codex']);
    await fs.writeFile(path.join(dir, CODEX_FILE), '{ not json');
    const r = await run(['install', '--harness', 'codex'], dir);
    expect(r.code).not.toBe(0);
    expect(r.stderr).toContain('not valid JSON');
    expect(await fs.readFile(path.join(dir, CODEX_FILE), 'utf8')).toBe('{ not json');
  });
});
